apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-demo
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-demo
  template:
    metadata:
      labels:
        app: java-demo
    spec:
      imagePullSecrets:
        - name: myregistry
      containers:
      - name: java-demo
        image: harbor.hitales.ai/cicd/java-demo:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo
  namespace: gitlab
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: java-demo
  selector:
    app: java-demo
  type: LoadBalancer
